name: Checkout
on: push
jobs:
  checkout_and_display_files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -la
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List Files After
        run: ls -a
